- build.gradle
- src/main/java/com/campfiredev/growtogether/bootcamp/controller/BootCampReviewController.java
- src/main/java/com/campfiredev/growtogether/bootcamp/dto/BootCampReviewCreateDto.java
- src/main/java/com/campfiredev/growtogether/bootcamp/dto/BootCampReviewRequest.java
- src/main/java/com/campfiredev/growtogether/bootcamp/dto/BootCampReviewResponseDto.java
- src/main/java/com/campfiredev/growtogether/bootcamp/dto/BootCampReviewUpdateDto.java
- src/main/java/com/campfiredev/growtogether/bootcamp/entity/BootCampReview.java
- src/main/java/com/campfiredev/growtogether/bootcamp/repository/BootCampReviewRepository.java
- src/main/java/com/campfiredev/growtogether/bootcamp/service/BootCampReviewService.java
- src/main/java/com/campfiredev/growtogether/exception/response/ErrorCode.java
- src/main/java/com/campfiredev/growtogether/member/config/AmazonS3Config.java
- src/main/java/com/campfiredev/growtogether/member/config/SecurityConfig.java
부트캠프 후기 CRUD
1. 부트캠프 후기 create -> 사용자 / 스킬 부분 로직은 추가해야 합니다. 
2. 부트캠프 후기 update 
3. 부트캠프 후기 delete
4. 부트캠프 후기 read -> 상제조회 아직 미구현 
5.    부트캠프 전체 조회 / 최신순 및 인기순  / 조회 한 페이지당 9개
------------------------------------------------------------------------------------------------------------------------
fix(Amazon S3 config): Amazon S3 관련 Access key cannot be null
1. @Value 주입 문제(Credentials 클래스는 static 내부 클래스라서 Spring이 Bean으로 관리하지 않음)
1-1. Credentials 클래스는 AmazonS3Config 내부의 static class이므로, @Value 어노테이션이 적용되지 않습니다.
1-2. @Value는 Spring 컨테이너에 의해 관리되는 Bean에서만 정상적으로 주입됩니다. 
현재 Credentials는 Bean으로 등록되지 않아 accessKey와 secretKey 값이 null이 됩니다.
1-3. 현재 인증 미 구현으로 SecurityConfig에서 /** 붙여 놓았습니다. 
1-4. 스크린샷 사진대로 입력하고 실행하면 현재 에러 없이 실행은 되고 있으나 이미지 업로드가 잘 되는지까지는 테스트는 안해본상황입니다. 
어떤 변경 사항이 있나요?
@Oh-Myeongjae …
> feat(부트캠프 후기): 부트캠프 후기

- src/main/java/com/campfiredev/growtogether/exception/response/ErrorCode.java
- src/main/java/com/campfiredev/growtogether/member/config/AmazonS3Config.java
- src/main/java/com/campfiredev/growtogether/skill/entity/SkillEntity.java
- src/main/java/com/campfiredev/growtogether/study/controller/StudyController.java
- src/main/java/com/campfiredev/growtogether/study/entity/Study.java
- src/main/java/com/campfiredev/growtogether/study/service/StudyService.java
- src/main/resources/data.sql
- src/test/java/com/campfiredev/growtogether/membetest/MemberServiceTest.java
- src/test/java/com/campfiredev/growtogether/study/service/StudyServiceTest.java
서버 실행시 기술스택 DB 자동으로 생성, 스터디 모집 게시글 작성시 작성자 항목 추가
어떤 변경 사항이 있나요?
> feat(기술스택, 스터디 모집게시글): 서버 실행시 기술스택 DB 자동으로 생성, 스터디 모집 게시글 작성시 작성자 항목 추가

- src/main/java/com/campfiredev/growtogether/exception/response/ErrorCode.java
- src/main/java/com/campfiredev/growtogether/member/config/AmazonS3Config.java
- src/main/java/com/campfiredev/growtogether/study/controller/StudyController.java
- src/main/java/com/campfiredev/growtogether/study/entity/SkillStudy.java
- src/main/java/com/campfiredev/growtogether/study/entity/Study.java
- src/main/java/com/campfiredev/growtogether/study/repository/StudyRepository.java
- src/main/java/com/campfiredev/growtogether/study/service/StudyService.java
- src/test/java/com/campfiredev/growtogether/study/service/StudyServiceTest.java
1. skilSutdy 엔티티에 유니크 제약조건 추가
2. 스터디 모집게시글 전체 조회 - 소프트 딜리트 안되어 있는것 중에 최신순으로 조회가능
3. 특정 모집게시글 조회
어떤 변경 사항이 있나요?
기본적인 기능 구현 완료 후 전체 게시글 조회 시 필터조건에 따른 코드가 추가,변경될수 있습니다.
> feat(스터디 게시글 조회): 스터디 게시글 전체조회, 특정 게시글 조회

- src/main/java/com/campfiredev/growtogether/bootcamp/controller/BootCampReviewController.java
- src/main/java/com/campfiredev/growtogether/bootcamp/dto/BootCampDetailResponseDto.java
- src/main/java/com/campfiredev/growtogether/bootcamp/dto/BootCampReviewCreateDto.java
- src/main/java/com/campfiredev/growtogether/bootcamp/dto/BootCampReviewResponseDto.java
- src/main/java/com/campfiredev/growtogether/bootcamp/dto/BootCampReviewUpdateDto.java
- src/main/java/com/campfiredev/growtogether/bootcamp/entity/BootCampComment.java
- src/main/java/com/campfiredev/growtogether/bootcamp/entity/BootCampReview.java
- src/main/java/com/campfiredev/growtogether/bootcamp/entity/BootCampSkill.java
- src/main/java/com/campfiredev/growtogether/bootcamp/entity/ReviewLike.java
- src/main/java/com/campfiredev/growtogether/bootcamp/repository/BootCampReviewRepository.java
- src/main/java/com/campfiredev/growtogether/bootcamp/repository/BootCampSkillRepository.java
- src/main/java/com/campfiredev/growtogether/bootcamp/repository/ReviewLikeRepository.java
- src/main/java/com/campfiredev/growtogether/bootcamp/service/BootCampReviewService.java
- src/main/java/com/campfiredev/growtogether/member/config/AmazonS3Config.java
- src/main/java/com/campfiredev/growtogether/member/repository/MemberRepository.java
1.  부트캠프 기술스택 매핑 엔티티 생성
2.  부트캠프 후기 사용자 필드 추가
3.  부트캠프 후기 생성시, 기술 스택 추가, 사용자 추가
4. 멘토님 리뷰 반영 
5. 부트캠프 후기 수정 및 삭제, 조회, 상세 조회 기능 구현 
6. 조회수 증가 및 좋아요 기능 구현
7. 동적 검색 (아직 미구현 , 이미지 업로드 아직 미구현) 
어떤 변경 사항이 있나요?
좋아요 기능 부분에 있어서  10초에서 30초 주기로 배치 작업을 통해 좋아요를 계산 하는 방식으로 할지, 고민을 하고 있는 상태이며 일단 기능 구현만 되도록 하였으며 또한 조회수 증가 역시,  
세션? 아니면 쿠키값을 이용하여 조회수 증가를 할지 고민을 하고 있습니다. 
@Oh-Myeongjae @focandlol @try3982
> feat(부트캠프 게시글 작성): 부트캠프 게시글 작성

- src/main/java/com/campfiredev/growtogether/bootcamp/controller/BootCampCommentController.java
- src/main/java/com/campfiredev/growtogether/bootcamp/dto/CommentRequest.java
- src/main/java/com/campfiredev/growtogether/bootcamp/dto/CommentResponseDto.java
- src/main/java/com/campfiredev/growtogether/bootcamp/dto/CommentUpdateRequest.java
- src/main/java/com/campfiredev/growtogether/bootcamp/entity/BootCampComment.java
- src/main/java/com/campfiredev/growtogether/bootcamp/repository/BootCampCommentRepository.java
- src/main/java/com/campfiredev/growtogether/bootcamp/service/BootCampCommentService.java
- src/main/java/com/campfiredev/growtogether/exception/response/ErrorCode.java
부트캠프 댓글 , 대댓글 crud
1.부트캠프 댓글 작성
2.부트캠프 댓글 수정
3.부트캠프 댓글 소프트 삭제
4.부트캠프 댓글 ,  대댓글까지 조회
어떤 변경 사항이 있나요?
> feat(부트캠프 댓글): 부트캠프 댓글

- src/main/java/com/campfiredev/growtogether/notification/controller/NotificationController.java
- src/main/java/com/campfiredev/growtogether/notification/dto/NotificationRequestDto.java
- src/main/java/com/campfiredev/growtogether/notification/repository/NotificationRepository.java
- src/main/java/com/campfiredev/growtogether/notification/service/Impl/NotificationServiceImpl.java
- src/main/java/com/campfiredev/growtogether/notification/service/NotificationService.java
1. 사용자의 읽지 않은 알림 목록 조회
2. 특정 알림 읽음 처리
어떤 변경 사항이 있나요?
> feat(Noti): Notification API

- src/main/java/com/campfiredev/growtogether/study/repository/notice/NoticeRepository.java
NoticeRepository findByStudyId 쿼리 수정
어떤 변경 사항이 있나요?
> fix: NoticeRepository findByStudyId 쿼리 수정

- src/main/java/com/campfiredev/growtogether/bootcamp/controller/BootCampCommentController.java
- src/main/java/com/campfiredev/growtogether/bootcamp/controller/BootCampReviewController.java
- src/main/java/com/campfiredev/growtogether/bootcamp/dto/BootCampReviewCreateDto.java
- src/main/java/com/campfiredev/growtogether/bootcamp/dto/BootCampReviewResponseDto.java
- src/main/java/com/campfiredev/growtogether/bootcamp/dto/BootCampReviewSearchRequest.java
- src/main/java/com/campfiredev/growtogether/bootcamp/dto/CommentRequest.java
- src/main/java/com/campfiredev/growtogether/bootcamp/dto/CommentUpdateRequest.java
- src/main/java/com/campfiredev/growtogether/bootcamp/entity/BootCampComment.java
- src/main/java/com/campfiredev/growtogether/bootcamp/entity/BootCampReview.java
- src/main/java/com/campfiredev/growtogether/bootcamp/entity/ReviewLike.java
- src/main/java/com/campfiredev/growtogether/bootcamp/repository/BootCampCommentRepository.java
- src/main/java/com/campfiredev/growtogether/bootcamp/repository/BootCampReviewRepositoryCustom.java
- src/main/java/com/campfiredev/growtogether/bootcamp/repository/BootCampReviewRepositoryImpl.java
- src/main/java/com/campfiredev/growtogether/bootcamp/repository/ReviewLikeRepository.java
- src/main/java/com/campfiredev/growtogether/bootcamp/service/BootCampCommentService.java
- src/main/java/com/campfiredev/growtogether/bootcamp/service/BootCampReviewService.java
- src/main/java/com/campfiredev/growtogether/bootcamp/strategy/WeightCalculateStrategy.java
- src/main/java/com/campfiredev/growtogether/bootcamp/strategy/WeightStrategy.java
- src/main/java/com/campfiredev/growtogether/bootcamp/type/ProgramCourse.java
- src/main/java/com/campfiredev/growtogether/common/config/SecurityConfig.java
- src/main/java/com/campfiredev/growtogether/exception/response/ErrorCode.java
- src/main/java/com/campfiredev/growtogether/notification/controller/SseNotiContoller.java
- src/main/java/com/campfiredev/growtogether/notification/dto/NotificationDto.java
- src/main/java/com/campfiredev/growtogether/notification/entity/Notification.java
- src/main/java/com/campfiredev/growtogether/notification/repository/NotificationRepository.java
- src/main/java/com/campfiredev/growtogether/notification/service/Impl/NotificationServiceImpl.java
- src/main/java/com/campfiredev/growtogether/notification/service/NotificationService.java
- src/main/java/com/campfiredev/growtogether/skill/repository/SkillRepository.java
1. api 파라미터에 Authenticate 추가
2. 파일 업로드 로직 추가
3. 검색 기능 로직 추가
4. 인기 게시글 로직 추가
전략 패턴을 사용하였고 , 가중치 계산을 통해서 인기 게시글을 구현하였습니다. 
(좋아요 * 5 , 조회수 *1 , 댓글 개수 * 3) 
전략 패턴을 사용한 이유는  `가중치 계산 방식에 변할 수 있는 가능성이 있기에 새로운 가중치 계산 방식에 추가가 쉽기에 선택`
5. 학습 언어, 프로그램 과정 필터 데이터 추가 
6. 내가 찜한 부트캠프 게시글 로직 추가
7. 알림 url 추가
어떤 변경 사항이 있나요?
@focandlol @Oh-Myeongjae @try3982
> feat(BootCamp): BootCamp 검색 , 인기 게시글

- src/main/java/com/campfiredev/growtogether/bootcamp/service/BootCampCommentService.java
- src/main/java/com/campfiredev/growtogether/common/config/SecurityConfig.java
- src/main/java/com/campfiredev/growtogether/notification/controller/NotificationController.java
- src/main/java/com/campfiredev/growtogether/notification/repository/EmitterRepository.java
- src/main/java/com/campfiredev/growtogether/notification/repository/Impl/EmiiterRepositoryImpl.java
- src/main/java/com/campfiredev/growtogether/notification/service/Impl/NotificationServiceImpl.java
- src/main/java/com/campfiredev/growtogether/notification/service/NotificationService.java
1. Notification auth 추가
2. 클라이언트와 서버간의 끊어짐 방지를 위한 heartbeat 메세지 추가
=> 아무 메세지가 안 올때 서버가 살아있다는 걸 확인 할 수 없어서 추가하였습니다. 
어떤 변경 사항이 있나요?
- [] 코드 리팩토링
@focandlol @Oh-Myeongjae @try3982
> feat(SSE): SSE 알림

- src/main/java/com/campfiredev/growtogether/exception/response/ErrorCode.java
- src/main/java/com/campfiredev/growtogether/member/entity/MemberEntity.java
- src/main/java/com/campfiredev/growtogether/study/controller/StudyCommentController.java
- src/main/java/com/campfiredev/growtogether/study/dto/StudyCommentDto.java
- src/main/java/com/campfiredev/growtogether/study/dto/StudyDTO.java
- src/main/java/com/campfiredev/growtogether/study/entity/Study.java
- src/main/java/com/campfiredev/growtogether/study/entity/StudyComment.java
- src/main/java/com/campfiredev/growtogether/study/repository/StudyCommentRepository.java
- src/main/java/com/campfiredev/growtogether/study/service/StudyCommentService.java
- src/main/java/com/campfiredev/growtogether/study/service/StudyService.java
1. 스터디 게시글 댓글기능 작성자 필드 추가
2. 스터디 모집 게시글 작성시 추가항목(모집 마감일, 메인일정 진행시간) 개발
3. 스터디 전체게시글 조회시 필요항목 추가
어떤 변경 사항이 있나요?
댓글 수정 요청시 이미 삭제된 댓글에 대해서 어떻게 핸들링하면 더 자연스러울까요?
1. 댓글을 엔티티에서 가져올때 삭제되지 않은 댓글과 작성자 이메일이 일치하는 댓글만 가져오기
2. 댓글을 엔티티에서 가져올때 삭제되지 않은 댓글을 우선 가져오고 권한이 있는지 여부를 확인하기
> 스터디 게시글 댓글 작성자 추가, 모집 게시글 작성시 입력항목 추가 

- src/main/java/com/campfiredev/growtogether/bootcamp/controller/BootCampCommentController.java
- src/main/java/com/campfiredev/growtogether/bootcamp/controller/BootCampReviewController.java
- src/main/java/com/campfiredev/growtogether/bootcamp/dto/BootCampReviewCreateDto.java
- src/main/java/com/campfiredev/growtogether/bootcamp/service/BootCampCommentService.java
- src/main/java/com/campfiredev/growtogether/bootcamp/service/BootCampReviewService.java
- src/main/java/com/campfiredev/growtogether/common/config/SecurityConfig.java
- src/main/java/com/campfiredev/growtogether/common/config/SwaggerConfig.java
- src/main/java/com/campfiredev/growtogether/member/entity/MemberEntity.java
- src/main/java/com/campfiredev/growtogether/notification/controller/NotificationController.java
- src/main/java/com/campfiredev/growtogether/notification/controller/SseNotiContoller.java
1. 인증 customUserDetail 방식 수정
2.  swagger JWT 인증을 적용한 API 문서화 (`http://localhost:8080/swagger-ui/index.html`)
3.  Member Entity 에러로  수정하였습니다.
어떤 변경 사항이 있나요?
@focandlol @Oh-Myeongjae @try3982
> feat(swagger): swagger

- src/main/java/com/campfiredev/growtogether/bootcamp/entity/BootCampComment.java
- src/main/java/com/campfiredev/growtogether/chat/ChatManager.java
- src/main/java/com/campfiredev/growtogether/chat/service/JwtInterceptor.java
- src/main/java/com/campfiredev/growtogether/common/config/SecurityConfig.java
- src/main/java/com/campfiredev/growtogether/exception/response/ErrorCode.java
- src/main/java/com/campfiredev/growtogether/member/entity/MemberEntity.java
- src/main/java/com/campfiredev/growtogether/member/util/JwtUtil.java
- src/main/java/com/campfiredev/growtogether/study/controller/attendance/AttendanceController.java
- src/main/java/com/campfiredev/growtogether/study/controller/feedback/FeedbackController.java
- src/main/java/com/campfiredev/growtogether/study/controller/join/JoinController.java
- src/main/java/com/campfiredev/growtogether/study/controller/notice/NoticeController.java
- src/main/java/com/campfiredev/growtogether/study/controller/schedule/ScheduleController.java
- src/main/java/com/campfiredev/growtogether/study/controller/vote/VoteController.java
- src/main/java/com/campfiredev/growtogether/study/dto/notice/NoticeListDto.java
- src/main/java/com/campfiredev/growtogether/study/repository/join/JoinRepository.java
- src/main/java/com/campfiredev/growtogether/study/service/join/JoinService.java
- src/main/java/com/campfiredev/growtogether/study/service/notice/NoticeService.java
- src/main/java/com/campfiredev/growtogether/study/service/schedule/ScheduleService.java
로그인한 사용자 정보 @AuthenticationPrincipal 사용하여 가져오도록 변경
spring security websocket 관련 permit
어떤 변경 사항이 있나요?
> refactor: 로그인한 사용자 정보 @AuthenticationPrincipal 사용하여 가져오도록 변경

- src/main/java/com/campfiredev/growtogether/exception/response/ErrorCode.java
- src/main/java/com/campfiredev/growtogether/study/dto/join/JoinDetailsDto.java
- src/main/java/com/campfiredev/growtogether/study/dto/schedule/ScheduleAttendeeDto.java
- src/main/java/com/campfiredev/growtogether/study/dto/schedule/ScheduleDto.java
- src/main/java/com/campfiredev/growtogether/study/repository/join/JoinRepository.java
- src/main/java/com/campfiredev/growtogether/study/service/join/JoinService.java
- src/main/java/com/campfiredev/growtogether/study/service/schedule/ScheduleService.java
- src/main/java/com/campfiredev/growtogether/study/service/vote/ChangeVoteProcessor.java
- src/main/java/com/campfiredev/growtogether/study/service/vote/KickVoteProcessor.java
투표 종료 시 sse 전송
강퇴 투표 종료
- 가결 시 : xxx님이 강퇴 되었습니다.
- 부결 시 : 강퇴 투표가 부결되었습니다.
일정 변경 투표 종료
- 가결 시 : 메인 일정이 변경 되었습니다.
- 부결 시 : 일정 변경 투표가 부결되었습니다.
변수명 변경
userName -> username
attendedNickNames -> attedees
creator -> author
스터디 참가 신청 시 validation 변경
RECRUIT -> !RECRUIT (현재 모집 중이 아니라면 예외)
어떤 변경 사항이 있나요?
> feat : 투표 종료 시 sse 알림

- src/main/java/com/campfiredev/growtogether/bootcamp/controller/BootCampCommentController.java
- src/main/java/com/campfiredev/growtogether/bootcamp/dto/BootCampReviewCreateDto.java
- src/main/java/com/campfiredev/growtogether/bootcamp/dto/BootCampReviewResponseDto.java
- src/main/java/com/campfiredev/growtogether/bootcamp/dto/BootCampReviewUpdateDto.java
- src/main/java/com/campfiredev/growtogether/bootcamp/dto/CommentRequest.java
- src/main/java/com/campfiredev/growtogether/bootcamp/dto/CommentResponseDto.java
- src/main/java/com/campfiredev/growtogether/bootcamp/dto/CommentUpdateRequest.java
- src/main/java/com/campfiredev/growtogether/bootcamp/service/BootCampCommentService.java
- src/main/java/com/campfiredev/growtogether/common/config/SecurityConfig.java
1. 프론트 분들이 부탁하신  응답 시 공통 변수명으로 변경
2. /api/bootcamp/programCourses , /api/bootcamp/skillName => 인증 안거치고 조회하는 방식 변경
어떤 변경 사항이 있나요?
> refactor(bootcamp): bootcamp

- src/main/java/com/campfiredev/growtogether/common/aop/RedissonLockAspect.java
- src/main/java/com/campfiredev/growtogether/common/config/SecurityConfig.java
- src/main/java/com/campfiredev/growtogether/member/entity/MemberEntity.java
- src/main/java/com/campfiredev/growtogether/member/filter/JwtAuthenticationFilter.java
- src/main/java/com/campfiredev/growtogether/member/util/JwtUtil.java
- src/main/java/com/campfiredev/growtogether/study/controller/BookmarkController.java
- src/main/java/com/campfiredev/growtogether/study/controller/StudyCommentController.java
- src/main/java/com/campfiredev/growtogether/study/controller/StudyController.java
- src/main/java/com/campfiredev/growtogether/study/dto/comment/StudyCommentDto.java
- src/main/java/com/campfiredev/growtogether/study/dto/post/PagedStudyDTO.java
- src/main/java/com/campfiredev/growtogether/study/dto/post/StudyDTO.java
- src/main/java/com/campfiredev/growtogether/study/entity/Study.java
- src/main/java/com/campfiredev/growtogether/study/entity/StudyComment.java
- src/main/java/com/campfiredev/growtogether/study/entity/join/StudyMemberEntity.java
- src/main/java/com/campfiredev/growtogether/study/service/bookmark/BookmarkService.java
- src/main/java/com/campfiredev/growtogether/study/service/comment/StudyCommentService.java
- src/main/java/com/campfiredev/growtogether/study/service/join/JoinService.java
- src/main/java/com/campfiredev/growtogether/study/service/post/StudyService.java
로그인 안한 유저도 스터디 게시글 조회가능 하게 로직 변경
어떤 변경 사항이 있나요?
> 로그인 안한 유저도 스터디 게시글 조회가능 하게 로직 변경

- src/main/java/com/campfiredev/growtogether/bootcamp/controller/BootCampReviewController.java
- src/main/java/com/campfiredev/growtogether/common/config/SecurityConfig.java
1. myLike api는  인증을 통과해야만 하는 api이므로 url 수정
어떤 변경 사항이 있나요?
> fix(bootcamp): 인증

- src/main/java/com/campfiredev/growtogether/point/service/PointService.java
어떤 변경 사항이 있나요?
redisson Rock 주석처리 했습니다.
> redisson Rock 주석

- src/main/java/com/campfiredev/growtogether/member/service/KakaoService.java
> transaction 제거

- src/main/java/com/campfiredev/growtogether/common/config/SecurityConfig.java
cors 프론트요청으로  SecurityConfit 클래스 CorsConfigurationSource()포트번호를 5173으로  변경하였습니다.
어떤 변경 사항이 있나요?
> cors 프론트요청으로 포트번호 변경하였습니다.

- src/main/java/com/campfiredev/growtogether/bootcamp/dto/BootCampReviewResponseDto.java
1.프론트에서 말씀주신 조회화면에 빠진  ProgramCousrse 필드를 추가하였습니다.
어떤 변경 사항이 있나요?
> fix(BootCampResponse): ProgramCousrse 필드 추가

- src/main/java/com/campfiredev/growtogether/common/config/SecurityConfig.java
- src/main/java/com/campfiredev/growtogether/exception/response/ErrorCode.java
- src/main/java/com/campfiredev/growtogether/member/controller/OAuthController.java
- src/main/java/com/campfiredev/growtogether/member/service/MemberService.java
- src/main/java/com/campfiredev/growtogether/study/repository/join/JoinRepository.java
- 회원가입시 사용중인 이메일, 등록된 전화번호, 닉네임 커스텀 예외처리로 변경하였습니다.
어떤 변경 사항이 있나요?
> 회원가입시 커스텀 예외처리

- src/main/java/com/campfiredev/growtogether/member/repository/MemberRepository.java
- src/main/java/com/campfiredev/growtogether/point/service/PointService.java
- src/main/java/com/campfiredev/growtogether/study/service/post/StudyService.java
- src/test/java/com/campfiredev/growtogether/PointServiceConcurrencyTest.java
Study 생성 시 발생하는 Timeout 예외 해결
포인트 관련 동시성 제어를 Pessimistic Lock으로 변경
어떤 변경 사항이 있나요?
> fix : study 생성 시 Timeout 예외 수정

- src/main/java/com/campfiredev/growtogether/point/service/PointService.java
- src/main/java/com/campfiredev/growtogether/study/controller/StudyCommentController.java
- src/main/java/com/campfiredev/growtogether/study/controller/StudyController.java
- src/main/java/com/campfiredev/growtogether/study/dto/post/StudyDTO.java
- src/main/java/com/campfiredev/growtogether/study/entity/Study.java
- src/main/java/com/campfiredev/growtogether/study/repository/StudyCommentRepository.java
- src/main/java/com/campfiredev/growtogether/study/repository/StudyRepository.java
- src/main/java/com/campfiredev/growtogether/study/service/comment/StudyCommentService.java
- src/main/java/com/campfiredev/growtogether/study/service/join/JoinService.java
- src/main/java/com/campfiredev/growtogether/study/service/post/StudyService.java
- src/main/resources/data.sql
스터디 모집 인기게시글 개발 및 댓글 무한스크롤 구현
어떤 변경 사항이 있나요?
> 스터디 모집 인기게시글 개발 및 댓글 무한스크롤 구현

- src/main/java/com/campfiredev/growtogether/study/dto/comment/StudyCommentDto.java
- src/main/java/com/campfiredev/growtogether/study/dto/post/StudyDTO.java
- src/main/java/com/campfiredev/growtogether/study/dto/post/StudyScheduleDto.java
- src/main/java/com/campfiredev/growtogether/study/dto/schedule/MainScheduleDto.java
- src/main/java/com/campfiredev/growtogether/study/entity/Study.java
- src/main/java/com/campfiredev/growtogether/study/service/post/StudyService.java
- src/test/java/com/campfiredev/growtogether/PointServiceConcurrencyTest.java
feat: 스터디 모집 마감시간 추가 및 메일일정 생성 로직 변경
어떤 변경 사항이 있나요?
> feat: 스터디 모집 마감시간 추가 및 메일일정 생성 로직 변경

- src/main/java/com/campfiredev/growtogether/bootcamp/dto/CommentResponseDto.java
- src/main/java/com/campfiredev/growtogether/bootcamp/service/BootCampReviewService.java
1. 게시글 전체 조회 시 댓글 개수 까지 같이 노출되도록
2. 댓글 조 회시, author , createdAt 나오도록 추가
어떤 변경 사항이 있나요?
> fix(BootCamp): 댓글 부분 수정

- src/main/java/com/campfiredev/growtogether/exception/response/ErrorCode.java
- src/main/java/com/campfiredev/growtogether/member/controller/ProfileController.java
- src/main/java/com/campfiredev/growtogether/member/service/MemberService.java
- 프로필 이미지 업로드시 예외처리 명확하게 변경하였습니다.
- 이미지key로 프로필을 업데이트하는걸 url로 업데이트하도록 수정하였습니다.
어떤 변경 사항이 있나요?
> 프로필 이미지 예외처리 및 url로 저장되도록 수정

- src/main/java/com/campfiredev/growtogether/member/controller/OAuthController.java
- 프론트에서 엑세스 토큰을 url에 넣어달라고 해서 요청사항 적용하여 수정하였습니다.
어떤 변경 사항이 있나요?
> 카카오로그인 fix

- src/main/java/com/campfiredev/growtogether/common/aop/RedissonLockAspect.java
- src/main/java/com/campfiredev/growtogether/point/service/PointService.java
- src/main/java/com/campfiredev/growtogether/study/controller/join/JoinController.java
- src/main/java/com/campfiredev/growtogether/study/service/attendance/AttendanceService.java
- src/main/java/com/campfiredev/growtogether/study/service/post/StudyService.java
- src/test/java/com/campfiredev/growtogether/PointServiceConcurrencyTest.java
비관적 락 적용 및 createStudy 시 동시성 이슈 확인 테스트입니다.
어떤 변경 사항이 있나요?
> test: 비관적 락 적용, 락 적용 테스트

- src/main/java/com/campfiredev/growtogether/study/service/schedule/ScheduleService.java
일정 삭제 버그 수정입니다.
어떤 변경 사항이 있나요?
> fix: 스케줄 삭제 수정

- src/main/java/com/campfiredev/growtogether/bootcamp/controller/BootCampReviewController.java
- src/main/java/com/campfiredev/growtogether/bootcamp/repository/BootCampReviewRepositoryCustom.java
- src/main/java/com/campfiredev/growtogether/bootcamp/repository/BootCampReviewRepositoryImpl.java
- src/main/java/com/campfiredev/growtogether/bootcamp/service/BootCampReviewService.java
- src/main/java/com/campfiredev/growtogether/notification/controller/SseNotiContoller.java
1. 검색 로직은 -> 페이징 x ,  전체글 보내주는 로직으로 변경
어떤 변경 사항이 있나요?
> refactor(BootCamp): 검색

- src/main/java/com/campfiredev/growtogether/chat/config/WebSocketConfig.java
- src/main/java/com/campfiredev/growtogether/chat/service/JwtInterceptor.java
- src/main/java/com/campfiredev/growtogether/common/config/SecurityConfig.java
- src/main/java/com/campfiredev/growtogether/study/controller/vote/VoteController.java
- src/main/java/com/campfiredev/growtogether/study/dto/join/StudyMemberInfoDto.java
- src/main/java/com/campfiredev/growtogether/study/dto/join/StudyMemberListDto.java
- src/main/java/com/campfiredev/growtogether/study/dto/vote/ChangeVoteDetailsDto.java
- src/main/java/com/campfiredev/growtogether/study/dto/vote/KickVoteDetailsDto.java
- src/main/java/com/campfiredev/growtogether/study/dto/vote/VoteDto.java
- src/main/java/com/campfiredev/growtogether/study/entity/vote/ChangeVoteEntity.java
- src/main/java/com/campfiredev/growtogether/study/service/join/JoinService.java
- src/main/java/com/campfiredev/growtogether/study/service/schedule/ScheduleService.java
- src/main/java/com/campfiredev/growtogether/study/service/vote/ChangeVoteProcessor.java
- src/main/java/com/campfiredev/growtogether/study/service/vote/VoteService.java
cors 설정 변경 -> setAllowedOriginPatterns(List.of("*")) 임시
WebSocketConfig cors 설정 변경 -> setAllowedOriginPatterns("*")
투표 세부 사항 조회 추가
- 강퇴 투표 : 강퇴자 닉네임, 프로필 이미지
- 일정 변경 투표 : 일정 내용, 이전 일정 시간, 변경 예정 일정 시간 등
일정 변경 투표 제목 변경
- String title = scheduleId + "번 스케줄 시간 변경 투표입니다."; ->  String title = scheduleEntity.getTitle() + " 스케줄 시간 변경 투표입니다.";
현재 진행중인 투표 리스트 조회 시 투표 타입 정확히 리턴하도록 변경
스터디 멤버 조회 시 프로필 이미지도 같이 리턴하도록 변경
ChangeVoteEntity -> ScheduleEntity 연관관계 설정
- scheduleId -> schedule 변경 -> 이에 따른 코드 변경
어떤 변경 사항이 있나요?
> refactor : 스터디 멤버 필드 추가, 투표 세부 사항 조회

- src/main/java/com/campfiredev/growtogether/notification/controller/SseNotiContoller.java
- src/main/java/com/campfiredev/growtogether/notification/service/Impl/NotificationServiceImpl.java
1. SSE 연결 시 메시지 JSON 형식으로 전송
2. 하트비트도 JSON 형식으로 전송
3. 이벤트 이름 notification 으로 통일
어떤 변경 사항이 있나요?
> fix(SSE): 알림 리턴값 수정

- src/main/java/com/campfiredev/growtogether/member/controller/MyPageController.java
- src/main/java/com/campfiredev/growtogether/member/dto/MyPageLikesDto.java
- src/main/java/com/campfiredev/growtogether/member/service/MyPageService.java
- src/main/java/com/campfiredev/growtogether/study/service/post/StudyService.java
Reverts CampusFireDev/growtogether_BE#88
> Revert "mypageFix"

- src/main/java/com/campfiredev/growtogether/study/service/post/StudyService.java
> StudyServiceFix

- src/main/java/com/campfiredev/growtogether/member/controller/OAuthController.java
- src/main/java/com/campfiredev/growtogether/member/dto/MyPageInfoDto.java
- src/main/java/com/campfiredev/growtogether/member/service/MyPageService.java
redirectUrl-> redirct_uri로 변경
어떤 변경 사항이 있나요?
- [] 버그 수정
> StudyService

- src/main/java/com/campfiredev/growtogether/member/entity/MemberEntity.java
- src/main/java/com/campfiredev/growtogether/member/service/MemberService.java
- src/main/java/com/campfiredev/growtogether/member/service/MyPageService.java
- src/main/java/com/campfiredev/growtogether/study/dto/join/JoinDetailsDto.java
- src/main/java/com/campfiredev/growtogether/study/repository/join/JoinRepository.java
- src/main/java/com/campfiredev/growtogether/study/service/feedback/FeedbackService.java
feedback validation 로직 변경 (스터디 종료 시에만 피드백 가능)
``
if(!COMPLETE.equals(studyMemberEntity.getStudy().getStudyStatus())){
throw new CustomException(INVALID_FEEDBACK_PERIOD);
}
``
스터디 참가자 세부 사항 조회 시 평점도 같이 조회되도록 변경
사용자 정보 변경 시 userSkills 관련 NullPointerException 발생으로 인해 임시 주석처리
멤버 생성 시 기본 rating 5.0 설정
어떤 변경 사항이 있나요?
@try3982 
사용자 회원가입 시 사용자가 선택한 기술스택 저장하는 부분이 없습니다. 추가 부탁드립니다.
> refactor : 신청자 세부 조회, 사용자 기본 rating 설정, 피드백

- src/main/java/com/campfiredev/growtogether/member/controller/MemberController.java
- src/main/java/com/campfiredev/growtogether/member/dto/MemberRegisterDto.java
- src/main/java/com/campfiredev/growtogether/member/dto/MemberResponseDto.java
- src/main/java/com/campfiredev/growtogether/member/dto/MyPageLikesDto.java
- src/main/java/com/campfiredev/growtogether/member/service/MemberService.java
- src/main/java/com/campfiredev/growtogether/member/service/MyPageService.java
부트캠프  좋아요 skillnames, programecourse 추가
어떤 변경 사항이 있나요?
> 부트캠프  좋아요 skillnames, programecourse

- src/main/java/com/campfiredev/growtogether/study/dto/join/JoinDetailsDto.java
참가 신청자 세부 정보 조회 시 포인트 조회 -> 평점 조회로 변경
필드 변경 points -> rating
from 메서드 builder() points() -> rating()으로 변경
어떤 변경 사항이 있나요?
> refactor: 참여 신청자 세부 조회 시 points -> rating 변경

- src/main/java/com/campfiredev/growtogether/common/config/SecurityConfig.java
- src/main/java/com/campfiredev/growtogether/payment/service/PaymentService.java
카카오 결제 연동 - approval_url 프론트 주소 등록하였습니다
어떤 변경 사항이 있나요?
> 카카오 결제 연동 - approval_url 프론트 주소 등록

- src/main/java/com/campfiredev/growtogether/member/service/MemberService.java
비밀번호 변경 페이지 이동 url 등록
어떤 변경 사항이 있나요?
> 비밀번호변경 url 등록

- src/main/java/com/campfiredev/growtogether/study/dto/vote/ChangeVoteDetailsDto.java
LocalDateTime -> LocalDate + LocalTime으로 나눠서 리턴
prevStartDate
- prevStartDate, prevStartTime
prevEndDate
- prevEndDate, prevEndTime
changeStartDate
- changeStartDate, chnageStartTime
changeEndDate
- changeEndDate, changeEndTime
어떤 변경 사항이 있나요?
> refactor: 진행 중인 투표 세부 조회 리턴 변경

- src/main/java/com/campfiredev/growtogether/member/service/MemberService.java
- src/main/java/com/campfiredev/growtogether/payment/controller/PaymentController.java
- src/main/java/com/campfiredev/growtogether/payment/service/PaymentService.java
> 비밀번호 변경 url 연동

- src/main/java/com/campfiredev/growtogether/study/dto/post/StudyDTO.java
- src/main/java/com/campfiredev/growtogether/study/repository/attendance/AttendanceRepository.java
- src/main/java/com/campfiredev/growtogether/study/repository/join/JoinRepository.java
- src/main/java/com/campfiredev/growtogether/study/repository/post/StudyRepositoryImpl.java
- src/main/java/com/campfiredev/growtogether/study/repository/schedule/ScheduleRepository.java
- src/main/java/com/campfiredev/growtogether/study/service/post/StudyService.java
- src/main/java/com/campfiredev/growtogether/study/service/schedule/ScheduleService.java
- src/main/java/com/campfiredev/growtogether/study/service/schedule/UpdateStudyStatusJob.java
스터디 게시글 정렬 에러 개선, 스터디 종료 api 추가, 스터디 게시글 조회시 항목추가
어떤 변경 사항이 있나요?
> 스터디 게시글 정렬 에러 개선, 스터디 종료 api 추가, 스터디 게시글 조회시 항목추가

- src/main/java/com/campfiredev/growtogether/bootcamp/service/BootCampCommentService.java
1. url  https://www.growtogether.site/bootcamp/ 로 수정
어떤 변경 사항이 있나요?
> fix(SSE): url 수정
